<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>2.1.0</VersionPrefix>
    <FileVersion>$(VersionPrefix).$(Revision)</FileVersion>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <Description>Provides FLAC (encoding, decoding and metadata) functionality for AudioWorks.</Description>
    <NuspecFile>Pack.nuspec</NuspecFile>
    <NuspecProperties>$(NuspecProperties);Configuration=$(Configuration.ToLowerInvariant())</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);Id=$(MSBuildProjectName)</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);Version=$(VersionPrefix)</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);Description=$(Description)</NuspecProperties>
  </PropertyGroup>
  
  <ItemGroup>
    <Content Include="runtimes\**" PackagePath="runtimes" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="..\..\AudioWorks.Extensibility\AudioWorks.Extensibility.csproj" />
  </ItemGroup>

  <!-- Enable SourceLink w/ custom .nuspec per https://github.com/dotnet/sourcelink/issues/1392 -->
  <Target Name="SetCustomNuspecProperties" BeforeTargets="GenerateNuspec" DependsOnTargets="InitializeSourceControlInformation">
    <PropertyGroup>
      <NuspecProperties>$(NuspecProperties);RepositoryType=$(RepositoryType)</NuspecProperties>
      <NuspecProperties>$(NuspecProperties);RepositoryUrl=$(RepositoryUrl)</NuspecProperties>
      <NuspecProperties>$(NuspecProperties);RepositoryBranch=$(RepositoryBranch)</NuspecProperties>
      <NuspecProperties>$(NuspecProperties);RepositoryCommit=$(RepositoryCommit)</NuspecProperties>
    </PropertyGroup>
  </Target>

</Project>
