name: Build and Test on Windows

on:
  push:
    branches: [ "main", "dev" ]
    paths-ignore:
      - 'azure-pipelines-*.yml'
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore AudioWorks\AudioWorks.sln
    - name: Build
      run: dotnet build AudioWorks\AudioWorks.sln --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude=[AudioWorks.*.Tests]*,[AudioWorks.TestUtilities]*